[workspace]

members = ["geometry", "rendering"]
resolver = "2"
[workspace.lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
suspicious = "warn"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "warn"
nursery = "warn"
module_name_repetitions = "allow"

[workspace.dependencies]
glam = { version = "0.27.0", features = ["approx", "glam-assert"] }
proptest = "1.4.0"
approx = "0.5.1"
